# Generated by Django 5.0.7 on 2024-07-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0003_voter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voter',
            new_name='Voters',
        ),
    ]
